apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: yourspace # {"$kpt-set":"namespace-setter"}
  name: auth-module-deployment
spec:
  replicas: 1 # {"$kpt-set":"auth-replicas"}
  template:
    spec:
      containers:
      - name: auth
        image: auth:1.7.9
